apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billingapp
  template:
    metadata:
      labels:
        app: billingapp
    spec:
      containers:
        - name: billingapp-container
          image: rajyavardhan36/billingsoftware:1.0.0-8
          env:
            - name: db.host
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: DB_HOST
            - name: db.port
              value: "3309"
            - name: db.name
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_name
            - name: db.username
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: DB_USERNAME
            - name: db.password
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: DB_PASSWORD
            - name: aws.access.key
              valueFrom:
                secretKeyRef:
                  name: awssm-secret
                  key: access-key
            - name: aws.secret.key
              valueFrom:
                secretKeyRef:
                  name: awssm-secret
                  key: secret-access-key
            - name: razorpay.key.id
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: RAZORPAY_KEY_ID
            - name: razorpay.key.secret
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: RAZORPAY_KEY_SECRET
          ports:
            - containerPort: 8022 # port on which container runs in cluster.

---
apiVersion: v1
kind: Service
metadata:
  name: billingapp-service
spec:
  selector:
    app: billingapp #linked to pod by matching the labels
  ports:
    - port: 80
    - targetPort: 8022 #Links the service to the pod